# Generated by Django 2.2.1 on 2019-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecKnowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vultitle', models.CharField(max_length=128)),
                ('vulgroup', models.CharField(max_length=128)),
                ('VulDesc', models.TextField()),
                ('VulCause', models.TextField()),
                ('AttackMethod', models.TextField()),
                ('VulSolution', models.TextField()),
                ('ReferDoc', models.TextField()),
                ('pubTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
