# Generated by Django 2.2 on 2019-04-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortScanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=64)),
                ('port_num', models.IntegerField()),
                ('port_status', models.CharField(max_length=64)),
            ],
        ),
    ]
